### ISSUE TITLE
Add a configuration support to hd

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/http-downloader#147]
Some flags are used a lot. Such as `--provider`, `--proxy-github`. We can save these flags into a config file. For instance, the config file could be `~/.config/hd/config.yaml`.

A sample config file structure could be:

```yaml
provider: github | gitee
proxy:
  github: gh.api.99988866.xyz
```
