### ISSUE TITLE
Provider a better way to choose the GitHub proxy

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/http-downloader#229]
Sometimes, we might meet the following errors when trying to use `gh.api.99988866.xyz`

`status code: 429`

We can record the GitHub proxy server into a config file. And mark the error when it occurs. So, it's possible to choose an available server automatically.

Since [v0.0.57](https://github.com/LinuxSuRen/http-downloader/releases/tag/v0.0.57), the config file `hd.yaml` looks like:

```yaml
fetch: true
goget: false
provider: gitee
proxy-github: gh.api.99988866.xyz
thread: 6
```

then, we can add the following items:

```yaml
proxy-github-candidates:
  - server: gh.api.99988866.xyz
     status: ok
     lastUsed: Thu Apr 14 21:32:08 CST 2022
  - server: ghproxy.com
     status: error
     lastUsed: Thu Apr 14 21:32:08 CST 2022
```
