### ISSUE TITLE
Support load default config files when installing a tool

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/http-downloader#248]
The potential configuration might be:
```yaml
filename: "{{.Name}}-{{.VersionNum}}-{{.OS}}-{{.Arch}}.tar.gz"
binary: containerd
additionBinaries:
- containerd-shim-runc-v2
defaultConfigFiles:
- os: linux
  path: /usr/local/lib/systemd/system/containerd.service
  content: |
    this is a fake file
- os: linux
  path: /etc/containerd/config.toml
  content: |
    [plugins]
      [plugins."io.containerd.grpc.v1.cri"]
        sandbox_image = "kubesphere/pause:3.2"
        [plugins."io.containerd.grpc.v1.cri".registry]
          [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
            [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
              endpoint = ["https://registry-1.docker.io"]
        [plugins."io.containerd.grpc.v1.cri".cni]
          bin_dir = "/opt/cni/bin"
          conf_dir = "/etc/cni/net.d"postInstalls:
- cmd: mkdir
  args:
  - -p
  - /usr/local/lib/systemd/system
- cmd: curl
  args:
  - https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
  - -o
  - /usr/local/lib/systemd/system/containerd.service
- cmd: systemctl
  args:
  - daemon-reload
- cmd: systemctl
  args:
  - enable
  - --now
  - containerd
categories:
- container
```
